clear all;

% Reading our cheque image to be used

% 49er Cheque (Wells Fargo)
%im = imread("49ercheque.jpg");

% US Banks Cheque
im = imread("USB.png");

% Running our PreProcessing function 
chequeReady = chequePreProcess(im);

%% Database Fill

% Filling Database for both banks 
% This Data was Generated by running IMCROP on both images

Fields = ["Bank Name"; "Name"; "Amount"; "Date"];
boundariesWF = ["NULL"; "578.5100, 549.5100, 1.076980000000000e+03, 77.980000"; "2948.51000000000, 660.510000000000, 446.980000000000, 86.9800000000000"; "2692.51000000000, 278.510000000000, 305.980000000000, 76.9800000000000"]
boundariesUS = ["NULL"; "797.510000000000, 582.510000000000, 1118.98000000000, 122.9800000000000"; "2759.51000000000, 618.510000000000, 461.980000000000, 101.980000000000"; "2249.51000000000, 360.510000000000, 581.980000000000, 110.980000000000"];

chequeBounds = table(Fields,boundariesWF);
chequeBounds = [chequeBounds table(boundariesUS)];

%% Switch Case

% Switch Case to Select the Bank
disp("Select the Bank for your Cheque : ")
disp("1. Wells Fargo Bank")
disp("2. US Bank")
n = input(['Type Selection : ']);

switch n
    case 1
        disp('Wells Fargo Data Loaded')

        chequeBounds.boundariesWF(1) = "Wells Fargo";

        % Loading Wells Fargo Database
        NameArea = str2num(chequeBounds.boundariesWF(2));
        AmountArea = str2num(chequeBounds.boundariesWF(3));
        DateArea = str2num(chequeBounds.boundariesWF(4));
    case 2
        disp('US Bank Data Loaded')

        chequeBounds.boundariesUS(1) = "US Bank";

        % Loading US Bank Database
        NameArea = str2num(chequeBounds.boundariesUS(2));
        AmountArea = str2num(chequeBounds.boundariesUS(3));
        DateArea = str2num(chequeBounds.boundariesUS(4));

    otherwise
        disp('Invalid Input')
end


%% EXTRACTING NAME

% Cropping according to the boundaries in the Database
nameCrop = imcrop(chequeReady, NameArea);
figure, imshow(nameCrop);

% Running OCR on the cropped section
nameResults = ocr(nameCrop);
name = strtrim(nameResults.Text)

%% EXTRACTING AMOUNT

% Cropping according to the boundaries in the Database
amountCrop = imcrop(chequeReady, AmountArea);

% Running OCR on the cropped section
amountResults = ocr(amountCrop);
amount = strtrim(amountResults.Text)

%% EXTRACTING DATE

% Cropping according to the boundaries in the Database
dateCrop = imcrop(chequeReady, DateArea);

% Running OCR on the cropped section
dateResults = ocr(dateCrop);
date = strtrim(dateResults.Text)


%% TABULAR FORM FOR EXTRACTED DATA

% Saving Extracted Data in a Tabular Form
Title = ["Bank Name" ; "Name on the Cheque"; "Amount" ; "Date"];

if n==1
    Data = [ chequeBounds.boundariesWF(1); name; amount; date];
else
    Data = [ chequeBounds.boundariesUS(1); name; amount; date];
end

ExtractedData = table(Title, Data);

ExtractedData